src/Entity/Produit.php
<?php

namespace App\Entity;

use App\Repository\ProduitRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;


#[UniqueEntity('nom', message: 'Ce produit existe déjà .')]
#[ORM\Entity(repositoryClass: ProduitRepository::class)]
class Produit
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?float $quantite = null;

    #[ORM\Column]
    private ?float $prix_vente = null;

    #[ORM\Column]
    #[Assert\PositiveOrZero]
    private ?float $quantite_vendues = null;

    #[ORM\Column]
    private ?bool $enPromotion = null;

    #[ORM\Column(nullable: true)]  // pourcentage_promo nullable
    #[Assert\Range(min: 0, max: 100, groups: ['Default'])]
    private ?int $pourcentage_promo = null;

    #[ORM\Column(type: 'datetime', nullable: true)]
    private ?\DateTimeInterface $date_debut_promo = null;

    #[ORM\Column(type: 'datetime', nullable: true)]
    private ?\DateTimeInterface $date_fin_promo = null;

 

    #[ORM\Column(nullable: true)]
    #[Assert\PositiveOrZero]
    private ?float $quantite_retourne = null;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $date_retour = null;

    #[ORM\Column(type: Types::STRING, length: 100)]
    #[Assert\Choice(choices: ['Disponible', 'En rupture'], message: "Le statut doit être 'Disponible' ou 'En rupture'.")]
    private ?string $statut = null;

    #[ORM\Column(type: Types::STRING, length: 100)]
    #[Assert\Choice(choices: ['Erreur de livraison', 'Produit endommagé'], message: "La raison doit être 'Erreur de livraison' ou 'Produit endommagé'.")]
    private ?string $raison_retour = null;

    #[ORM\ManyToOne(targetEntity: Stock::class, inversedBy: 'produits')]
    #[ORM\JoinColumn(name: 'stock_id', referencedColumnName: 'id', onDelete: 'CASCADE')]
    private ?Stock $stock = null;

    /**
     * @var Collection<int, Vente>
     */
    #[ORM\OneToMany(targetEntity: Vente::class, mappedBy: 'produit')]
    private Collection $ventes;

    #[ORM\Column(length: 255)]
    private ?string $nom = null;

    #[ORM\Column(length: 255)]
    private ?string $image = null;

    #[ORM\Column(length: 255)]
    private ?string $description_globale = null;

    #[ORM\Column(length: 255)]
    private ?string $description_detaille = null;

    #[ORM\Column(length: 255)]
    private ?string $categorie = null;



    

    public function __construct()
    {
        $this->ventes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getQuantite(): ?float
    {
        return $this->quantite;
    }

    public function setQuantite(float $quantite): static
    {
        $this->quantite = $quantite;

        return $this;
    }

    public function getPrixVente(): ?float
    {
        return $this->prix_vente;
    }

    public function setPrixVente(float $prix_vente): static
    {
        $this->prix_vente = $prix_vente;

        return $this;
    }

    public function getQuantiteVendues(): ?float
    {
        return $this->quantite_vendues;
    }

    public function setQuantiteVendues(float $quantite_vendues): static
    {
        $this->quantite_vendues = $quantite_vendues;

        return $this;
    }

    public function isEnPromotion(): ?bool
    {
        return $this->enPromotion;
    }

    public function setEnPromotion(bool $enPromotion): static
    {
        $this->enPromotion = $enPromotion;

        return $this;
    }

    public function getPourcentagePromo(): ?int
    {
        return $this->pourcentage_promo;
    }

    public function setPourcentagePromo(?int $pourcentage_promo): static
{
    $this->pourcentage_promo = $pourcentage_promo;
    return $this;
}

    public function getDateDebutPromo(): ?\DateTimeInterface
    {
        return $this->date_debut_promo;
    }

    public function setDateDebutPromo(?\DateTimeInterface $date_debut_promo): static
{
    $this->date_debut_promo = $date_debut_promo;
    return $this;
}

    public function getDateFinPromo(): ?\DateTimeInterface
    {
        return $this->date_fin_promo;
    }

    public function setDateFinPromo(?\DateTimeInterface $date_fin_promo): static
{
    $this->date_fin_promo = $date_fin_promo;
    return $this;
}

    public function getQuantiteRetourne(): ?float
    {
        return $this->quantite_retourne;
    }

    public function setQuantiteRetourne(?float $quantite_retourne): static
    {
        $this->quantite_retourne = $quantite_retourne;

        return $this;
    }

    public function getDateRetour(): ?\DateTimeInterface
    {
        return $this->date_retour;
    }

    public function setDateRetour(?\DateTimeInterface $date_retour): static
    {
        $this->date_retour = $date_retour;

        return $this;
    }

    public function getStatut(): ?string
    {
        return $this->statut;
    }

    public function setStatut(string $statut): self
    {
        if (!in_array($statut, ['Disponible', 'En rupture'])) {
            throw new \InvalidArgumentException("Le statut doit être 'Disponible' ou 'En rupture'.");
        }

        $this->statut = $statut;
        return $this;
    }

    public function getRaisonRetour(): ?string
    {
        return $this->raison_retour;
    }

    public function setRaisonRetour(string $raison_retour): self
    {
        if (!in_array($raison_retour, ['Erreur de livraison', 'Produit endommagé'])) {
            throw new \InvalidArgumentException("La raison doit être 'Erreur de livraison' ou 'Produit endommagé'.");
        }

        $this->raison_retour = $raison_retour;
        return $this;
    }

    public function getStock(): ?Stock
    {
        return $this->stock;
    }

    public function setStock(?Stock $stock): static
    {
        $this->stock = $stock;

        return $this;
    }

   // Pour le nom du produit
public function getNom(): ?string
{
    return $this->nom;
}

// Pour le nom du stock
public function getStockNom(): ?string
{
    return $this->stock ? $this->stock->getNom() : null;
}


    /**
     * @return Collection<int, Vente>
     */
    public function getVentes(): Collection
    {
        return $this->ventes;
    }

    public function addVente(Vente $vente): static
    {
        if (!$this->ventes->contains($vente)) {
            $this->ventes->add($vente);
            $vente->setProduit($this);
        }

        return $this;
    }

    public function removeVente(Vente $vente): static
    {
        if ($this->ventes->removeElement($vente)) {
            // set the owning side to null (unless already changed)
            if ($vente->getProduit() === $this) {
                $vente->setProduit(null);
            }
        }

        return $this;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): static
    {
        $this->image = $image;

        return $this;
    }

    public function getDescriptionGlobale(): ?string
    {
        return $this->description_globale;
    }

    public function setDescriptionGlobale(string $description_globale): static
    {
        $this->description_globale = $description_globale;

        return $this;
    }

    public function getDescriptionDetaille(): ?string
    {
        return $this->description_detaille;
    }

    public function setDescriptionDetaille(string $description_detaille): static
    {
        $this->description_detaille = $description_detaille;

        return $this;
    }

    public function getCategorie(): ?string
    {
        return $this->categorie;
    }

    public function setCategorie(string $categorie): self
    {
        if(!in_array($categorie,['Fruits','Légumes','Déchets'])){
            throw new \InvalidArgumentException("la catégorie doit etre 'Fruits','Légumes','Déchets' ");
        }
        $this->categorie = $categorie;

        return $this;
    }


    
}

src/Controller/ProduitController.php
<?php

namespace App\Controller;

use App\Entity\Produit;
use App\Form\ProduitType;
use App\Repository\ProduitRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Pagerfanta\Doctrine\ORM\QueryAdapter;
use Pagerfanta\View\TwitterBootstrap5View;
use App\Entity\User;
use Symfony\Component\HttpFoundation\Session\SessionInterface;
use Knp\Component\Pager\PaginatorInterface;
use Liip\ImagineBundle\Imagine\Cache\CacheManager;

#[Route('/produit')]
final class ProduitController extends AbstractController
{
    #[Route(name: 'app_produit_index', methods: ['GET'])]
    public function index(ProduitRepository $produitRepository, Request $request, SessionInterface $session, EntityManagerInterface $entityManager, PaginatorInterface $paginator): Response
    {
        $loggedInUserId = $session->get('user_id');
    
        if (!$loggedInUserId) {
            return $this->redirectToRoute('app_user_login');
        }
    
        $loggedInUser = $entityManager->getRepository(User::class)->find($loggedInUserId);
    
        if (!$loggedInUser) {
            return $this->redirectToRoute('app_user_login');
        }
        
        // Get selected category from request
        $category = $request->query->get('category');
        
        // Get products by category (or all if no category is selected)
        $query = $produitRepository->findByCategory($category);
        
        $pagination = $paginator->paginate(
            $query,
            $request->query->getInt('page', 1),
            4
        );
        
        $mapboxApiKey = $_ENV['MAPBOX_API_KEY'];
    
        return $this->render('produit/index.html.twig', [
            'loggedInUser' => $loggedInUser,
            'pagination' => $pagination,
            'MAPBOX_API_KEY' => $mapboxApiKey,
            'currentCategory' => $category,
        ]);
    }

    #[Route('/{id}', name: 'app_produit_show', methods: ['GET'])]
    public function show(Produit $produit, SessionInterface $session, EntityManagerInterface $entityManager, CacheManager $cacheManager): Response
    {
        $loggedInUserId = $session->get('user_id');
    
        if (!$loggedInUserId) {
            return $this->redirectToRoute('app_user_login');
        }
    
        $loggedInUser = $entityManager->getRepository(User::class)->find($loggedInUserId);
    
        if (!$loggedInUser) {
            return $this->redirectToRoute('app_user_login');
        }
    
        // Generate filtered image path for 'thumbnail' filter
        $imagePath = $cacheManager->getBrowserPath('img/stock/' . $produit->getImage(), 'thumbnail');
        
        // Generate original image path for backup
        $originalImagePath = $this->getParameter('kernel.project_dir') . '/public/img/stock/' . $produit->getImage();
        $imageExists = file_exists($originalImagePath);
        
        // Get related products (you may want to implement this method in your repository)
        // Example: $relatedProducts = $produitRepository->findRelatedProducts($produit->getId(), $produit->getCategory(), 4);
        
        return $this->render('produit/show.html.twig', [
            'produit' => $produit,
            'loggedInUser' => $loggedInUser,
            'imagePath' => $imagePath,
            'imageExists' => $imageExists,
            // 'relatedProducts' => $relatedProducts, // Uncomment if you implement this
        ]);
    }
}

templates/produit/_delete_form.html.twig
<form method="post" action="{{ path('app_produit_delete', {'id': produit.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ produit.id) }}">
    <button class="btn">Delete</button>
</form>

templates/produit/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}

    <button  class="danger">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/produit/show.html.twig
{% extends 'user/client.html.twig' %}

{% block title %}Produit{% endblock %}

{% block body %}
   
    <!-- Start Shop 
    ============================================= -->
    <div class="validtheme-shop-single-area default-padding">
        <div class="container">
            <div class="product-details">
                <div class="row">

                    <div class="col-lg-6">
                        <div class="product-thumb">
                            <div id="timeline-carousel" class="carousel slide" data-bs-ride="carousel">

                                <div class="carousel-inner item-box">
                                    <div class="carousel-item active product-item">
                                        <a  class="item popup-gallery">
                                           <img src="{{ asset('img/stock/' ~ produit.image) }}" alt="Image du produit">
                                        </a>
                                        {% if produit.enPromotion %}
                                            <span class="onsale theme">-{{ produit.pourcentagePromo }}%</span>
                                        {% endif %}
                                    </div>
                                    <div class="carousel-item product-item">
                                        <a href="assets/img/products/2.png" class="item popup-gallery">
                                             <img src="{{ asset('img/stock/' ~ produit.image) }}" alt="Image du produit" >
                                        </a>
                                        {% if produit.enPromotion %}
                                            <span class="onsale theme">-{{ produit.pourcentagePromo }}%</span>
                                        {% endif %}
                                    </div>
                                   
                                </div>

                                 <!-- Carousel Indicators -->
  <div class="carousel-indicators">
                                    <div class="product-gallery-carousel swiper">
                                        <!-- Additional required wrapper -->
                                        <div class="swiper-wrapper">
                                            <div class="swiper-slide">
                                                <div class="item active" data-bs-target="#timeline-carousel" data-bs-slide-to="0" aria-current="true">
                                                      <img src="{{ asset('img/stock/' ~ produit.image) | imagine_filter('thumbnail') }}" alt="Image du produit">
                                                </div>
                                            </div>
                                           
                                        </div>
                                    </div>
                                </div>
                                
                                <!-- End Carousel Content -->
                               
                            </div>
                        </div>
                    </div>

                    <div class="col-lg-6">
                        <div class="single-product-contents">
                            <div class="summary-top-box">
                                <div class="product-tags">
                                    
                                   
                                </div>
                                <div class="review-count">
                                   
                                </div>
                            </div>
                            <h2 class="product-title">
                                {{ produit.nom  }}  
                            </h2>
                            <div class="price">
                                {% if produit.enPromotion %}
                                    <span><del>{{ produit.prixVente }} DT</del></span>
                                    {% set prixPromo = produit.prixVente - (produit.prixVente * produit.pourcentagePromo / 100) %}
                                    <span>{{ prixPromo|number_format(2, '.', '') }} DT</span>
                                {% else %}
                                    <span>{{ produit.prixVente }} DT</span>
                                {% endif %}
                            </div>
                            <span>Quantité = {{ produit.quantite }} </span>
                            <div class="product-stock validthemes-in-stock">
                                <span>In Stock</span>
                                 
                            </div>
                            
                            <p>
                                {{ produit.DescriptionGlobale}}
                            </p>
                            <div class="product-purchase-list">
                               
                                <a href="app_vente_new" class="btn secondary btn-theme btn-sm animation">
                                    <i class="fas fa-shopping-cart"></i>
                                    Add to cart
                                </a>
                              
                            </div>
                            <div class="product-estimate-delivary">
                                <i class="fas fa-box-open"></i>
                                <strong> 2-day Delivery</strong>
                                <span>Speedy and reliable parcel delivery!</span>
                            </div>
                           
                        </div>
                    </div>
                </div>
            </div>

            <!-- Product Bottom Info  -->
            <div class="single-product-bottom-info">
                <div class="row">
                    <div class="col-lg-12">
                        <!-- Tab Nav -->
                        <div class="nav nav-tabs" id="nav-tab" role="tablist">
                            <button class="nav-link active" id="description-tab-control" data-bs-toggle="tab" data-bs-target="#description-tab" type="button" role="tab" aria-controls="description-tab" aria-selected="true">
                                Description
                            </button>
                            
                            

                        </div>
                        <!-- End Tab Nav -->
                        <!-- Start Tab Content -->
                        <div class="tab-content tab-content-info" id="myTabContent">

                            <!-- Tab Single -->
                            <div class="tab-pane fade show active" id="description-tab" role="tabpanel" aria-labelledby="description-tab-control">
                                
                                <ul> 
                                    <p>  {{ produit.DescriptionDetaille}}</p> 
                                    
                                </ul>
                            </div>
                            <!-- End Single -->

                        </div>
                        <!-- End Tab Content -->
                    </div>
                </div>
            </div>
            <!-- End Product Bottom Info  -->


           
        </div>
    </div>

{% endblock %}

templates/produit/showback.html.twig
{% extends 'baseAdmin.html.twig' %}

{% block title %}Détail du Produit{% endblock %}

{% block body %}
<div class="container py-4">
    <div class="card shadow border-0 rounded-3 overflow-hidden">
        <div class="card-header text-white" style="background-color: #198754;">
            <h2 class="my-2">Détail du Produit</h2>
        </div>
        
        <div class="card-body">
            <div class="row g-4">
                <!-- Image du produit -->
                <div class="col-md-4 text-center">
                    <div class="card h-100 border-0 shadow-sm">
                        <div class="card-body d-flex align-items-center justify-content-center">
                            {% if produit.image %}
                                <img src="{{ asset('img/stock/' ~ produit.image) }}" alt="Image du produit" class="img-fluid rounded" style="max-height: 280px; width: auto;">
                            {% else %}
                                <div class="text-muted">
                                    <i class="fas fa-image fa-5x mb-3"></i>
                                    <p>Aucune image disponible</p>
                                </div>
                            {% endif %}
                        </div>
                    </div>
                </div>
                
                <!-- Informations principales -->
                <div class="col-md-8">
                    <div class="row g-3">
                        <!-- Nom et ID -->
                        <div class="col-12">
                            <div class="card border-0 shadow-sm">
                                <div class="card-body">
                                    <h3 class="card-title mb-0" style="color: #198754;">{{ produit.nom }}</h3>
                                    <small class="text-muted">ID: {{ produit.id }}</small>
                                </div>
                            </div>
                        </div>
                        
                        <!-- Prix et statut de stock -->
                        <div class="col-md-6">
                            <div class="card border-0 shadow-sm h-100">
                                <div class="card-body">
                                    <h5 class="card-title"><i class="fas fa-tag me-2"></i>Prix</h5>
                                    <div class="d-flex align-items-baseline">
                                        {% if produit.enPromotion %}
                                            <h3 class="me-2" style="color: #198754;">
                                                {{ (produit.prixVente * (1 - produit.pourcentagePromo / 100))|number_format(2, ',', ' ') }} DT
                                            </h3>
                                            <p class="text-decoration-line-through text-muted">
                                                {{ produit.prixVente|number_format(2, ',', ' ') }} DT
                                            </p>
                                        {% else %}
                                            <h3 style="color: #198754;">{{ produit.prixVente|number_format(2, ',', ' ') }} DT</h3>
                                        {% endif %}
                                    </div>
                                    
                                    <div class="mt-2">
                                        <span class="badge {{ produit.quantite > 10 ? 'bg-success' : (produit.quantite > 0 ? 'bg-warning' : 'bg-danger') }}">
                                            {{ produit.quantite > 10 ? 'En stock' : (produit.quantite > 0 ? 'Stock limité' : 'Épuisé') }}
                                        </span>
                                        <span class="ms-2 text-muted">({{ produit.quantite }} unités)</span>
                                    </div>
                                </div>
                            </div>
                        </div>
                        
                        <!-- Promotion -->
                        <div class="col-md-6">
                            <div class="card border-0 shadow-sm h-100">
                                <div class="card-body">
                                    <h5 class="card-title"><i class="fas fa-percent me-2"></i>Promotion</h5>
                                    {% if produit.enPromotion %}
                                        <div class="badge bg-danger mb-2">-{{ produit.pourcentagePromo }}%</div>
                                        <p class="mb-1">
                                            <i class="far fa-calendar-alt me-1"></i> Début: 
                                            {{ produit.dateDebutPromo ? produit.dateDebutPromo|date('d/m/Y') : 'N/A' }}
                                        </p>
                                        <p>
                                            <i class="far fa-calendar-alt me-1"></i> Fin: 
                                            {{ produit.dateFinPromo ? produit.dateFinPromo|date('d/m/Y') : 'N/A' }}
                                        </p>
                                    {% else %}
                                        <p class="text-muted">Aucune promotion en cours</p>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            
            <!-- Description -->
            <div class="row mt-4">
                <div class="col-12">
                    <div class="card border-0 shadow-sm">
                        <div class="card-header bg-light">
                            <h5 class="mb-0"><i class="fas fa-align-left me-2"></i>Description</h5>
                        </div>
                        <div class="card-body">
                            <h6 style="color: #198754;">Description globale</h6>
                            <p>{{ produit.DescriptionGlobale ?: 'Aucune description globale' }}</p>
                            
                            <h6 style="color: #198754;" class="mt-3">Description détaillée</h6>
                            <p>{{ produit.DescriptionDetaille ?: 'Aucune description détaillée' }}</p>
                        </div>
                    </div>
                </div>
            </div>
            
            <!-- Statistiques de vente -->
            <div class="row mt-4">
                <div class="col-12">
                    <div class="card border-0 shadow-sm">
                        <div class="card-header bg-light">
                            <h5 class="mb-0"><i class="fas fa-chart-bar me-2"></i>Statistiques de vente</h5>
                        </div>
                        <div class="card-body">
                            <div class="row">
                                <div class="col-md-4">
                                    <div class="d-flex align-items-center">
                                        <div class="rounded-circle p-3 me-3" style="background-color: rgba(25, 135, 84, 0.1);">
                                            <i class="fas fa-shopping-cart" style="color: #198754;"></i>
                                        </div>
                                        <div>
                                            <h6 class="mb-0">Quantité vendue</h6>
                                            <h4 class="mt-1 mb-0">{{ produit.quantiteVendues ?: '0' }}</h4>
                                        </div>
                                    </div>
                                </div>
                                
                                <div class="col-md-4">
                                    <div class="d-flex align-items-center">
                                        <div class="rounded-circle bg-danger bg-opacity-10 p-3 me-3">
                                            <i class="fas fa-undo text-danger"></i>
                                        </div>
                                        <div>
                                            <h6 class="mb-0">Quantité retournée</h6>
                                            <h4 class="mt-1 mb-0">{{ produit.quantiteRetourne ?: '0' }}</h4>
                                        </div>
                                    </div>
                                </div>
                                
                                <div class="col-md-4">
                                    <div class="d-flex align-items-center">
                                        <div class="rounded-circle p-3 me-3" style="background-color: rgba(25, 135, 84, 0.1);">
                                            <i class="fas fa-percentage" style="color: #198754;"></i>
                                        </div>
                                        <div>
                                            <h6 class="mb-0">Taux de retour</h6>
                                            <h4 class="mt-1 mb-0">
                                                {% if produit.quantiteVendues > 0 %}
                                                    {{ ((produit.quantiteRetourne / produit.quantiteVendues) * 100)|number_format(1) }}%
                                                {% else %}
                                                    0%
                                                {% endif %}
                                            </h4>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            
                            {% if produit.quantiteRetourne > 0 %}
                            <div class="mt-4">
                                <h6 class="text-danger"><i class="fas fa-exclamation-circle me-2"></i>Informations de retour</h6>
                                <div class="row mt-2">
                                    <div class="col-md-6">
                                        <p><strong>Date du dernier retour:</strong> {{ produit.dateRetour ? produit.dateRetour|date('d/m/Y') : 'N/A' }}</p>
                                    </div>
                                    <div class="col-md-6">
                                        <p><strong>Raison du retour:</strong> {{ produit.raisonRetour ?: 'Non spécifiée' }}</p>
                                    </div>
                                </div>
                            </div>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
        
        <div class="card-footer bg-light">
            <div class="d-flex gap-2">
                <a href="{{ path('app_produitback_index') }}" class="btn btn-secondary">
                    <i class="fas fa-arrow-left me-1"></i> Retour à la liste
                </a>
                <a href="{{ path('app_produit_edit', {'id': produit.id}) }}" class="btn" style="background-color: #198754; color: white;">
                    <i class="fas fa-edit me-1"></i> Modifier
                </a>
                <div class="ms-auto">
                    {{ include('produit/_delete_form.html.twig') }}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/produit/stats.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <h1>Statistiques des Produits</h1>
    <canvas id="myChart" width="400" height="200"></canvas>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <script>
        var ctx = document.getElementById('myChart').getContext('2d');
        var myChart = new Chart(ctx, {
            type: 'bar',
            data: {{ chartData|raw }},
            options: {
                scales: {
                    y: {
                        beginAtZero: true
                    }
                }
            }
        });
    </script>
    
{% endblock %}