src/Entity/Atelier.php
<?php

namespace App\Entity;
use Doctrine\ORM\EntityManagerInterface;
use App\Repository\AtelierRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert ;
#[ORM\Entity(repositoryClass: AtelierRepository::class)]
class Atelier
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;


    #[ORM\Column(length: 100)]
    #[Assert\NotBlank(message: "Le nom de l'atelier ne peut pas être vide.")]
    #[Assert\Length(
        max: 15, 
        maxMessage: "Le nom de l'atelier ne peut pas dépasser 30 caractères."
    )]
    #[Assert\Regex(
    pattern: "/^[a-zA-Z0-9À-ÿ\s]+$/",
    message: "Le nom de l'atelier doit contenir uniquement des lettres alphabétiques et des chiffres."
)]//controle de saisie 
    private ?string $nom = null;

    #[ORM\Column(length: 255)]
    private ?string $description = null;

    #[Assert\NotBlank(message: "La date de l'atelier ne peut pas être vide.")]
#[Assert\Type(type: \DateTimeInterface::class, message: "La date doit être au bon format.")]
#[Assert\GreaterThanOrEqual(
    value: "today",
    message: "l'atelier ne peux pas prendre une date déja passée"
)]
    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date_atelier = null;

    #[ORM\Column]
    #[Assert\NotBlank(message: "La capacite maximal de l'atelier ne peut pas être vide.")]
    #[Assert\Range(
        min: 1, 
        max: 500, 
        notInRangeMessage: "La capacité doit être comprise entre {{ min }} et {{ max }}."
    )]//controle de saisie 
    private ?int $capacite_max = null;

    #[ORM\Column]
    #[Assert\NotBlank(message: "Le prix ne peut pas être vide.")] 
    #[Assert\Positive(message: "Le prix doit être strictement positif.")]
    private ?float $prix = null;

    #[ORM\Column(type: Types::STRING, length: 100)]
    #[Assert\NotBlank(message: "Tu dois choisir une option.")]

    #[Assert\Choice(choices: ['ouvert','complet','annulé'],message: "le statut doit étre 'ouvert','complet','annulé' ")]
    private ?string $statut = 'ouvert';

    #[ORM\Column(type: Types::STRING, length: 100)]
    #[Assert\NotBlank(message: "Tu dois choisir une option.")] 

    #[Assert\Choice(choices: ['agriculteur','client','employee'],message: "le role doit étre 'agriculteur','client','employee' ")]
    private ?string $Role = 'client';


    #[ORM\Column (nullable:true)]
    private ?int $nbrplacedispo = null;

    /**
     * @var Collection<int, User>
     */
    #[ORM\ManyToMany(targetEntity: User::class, inversedBy: 'ateliers')]
    private Collection $users;

    #[ORM\Column(length: 255)]
    private ?string $photo = null;

    /**
     * @var Collection<int, Dechet>
     */
    #[ORM\OneToMany(targetEntity: Dechet::class, mappedBy: 'dechet')]
    private Collection $dechet;

    #[ORM\Column(type: "string", length: 255)]
    private string $title;

    #[ORM\Column(type: "datetime")]
    private \DateTimeInterface $startAt;

    #[ORM\Column(type: "datetime", nullable: true)]
    private ?\DateTimeInterface $endAt = null;

 

    public function __construct()
    {
        $this->users = new ArrayCollection();
        $this->nbrplacedispo = $this->capacite_max;
        $this->dechet = new ArrayCollection(); 
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getDateAtelier(): ?\DateTimeInterface
    {
        return $this->date_atelier;
    }

    public function setDateAtelier(\DateTimeInterface $date_atelier): static
    {
        $this->date_atelier = $date_atelier;

        return $this;
    }

    public function getCapaciteMax(): ?int
    {
        return $this->capacite_max;
    }

    public function setCapaciteMax(int $capacite_max): static
    {
        $this->capacite_max = $capacite_max;
        $this->nbrplacedispo = $capacite_max; 
        return $this;
    }

    public function getPrix(): ?float
    {
        return $this->prix;
    }

    public function setPrix(float $prix): static
    {
        $this->prix = $prix;

        return $this;
    }

       public function getStatut(): ?string
    {
        return $this->statut;
    }

    public function setStatut(string $statut): self
    {   $statut='ouvert';
        if(!in_array($statut,['ouvert','complet','annulé'])){
            throw new \InvalidArgumentException("le statut doit etre 'ouvert','complet','annulé' ");
        }
        $this->statut = $statut;
        return $this;
    }

    public function getRole(): ?string
    {
        return $this->Role;
    }

    public function setRole(string $Role): self
    {        if(!in_array($Role,['agriculteur','client','employee'])){
                throw new \InvalidArgumentException("le role doit etre 'agriculteur','client','employee'");
    }    
                $this->Role = $Role;
                return $this;

    }

    /**
     * @return Collection<int, User>
     */
    public function getUsers(): Collection
    {
        return $this->users;
    }

    public function addUser(User $user): static
    {
        if (!$this->users->contains($user)) {
            $this->users->add($user);
        }
    
        return $this;
    }
    

    public function removeUser(User $user): static
    {
        $this->users->removeElement($user);
    
        // Incrémente la place disponible si nécessaire
        $this->nbrplacedispo++;
        return $this;
    }

    public function getPhoto(): ?string
    {
        return $this->photo;
    }

    public function setPhoto(string $photo): static
    {
        $this->photo = $photo;

        return $this;
    }

    public function getNbrplacedispo(): ?int
    {
        return $this->nbrplacedispo;
    }

    public function setNbrplacedispo(int $nbrplacedispo): static
    {
        $this->nbrplacedispo = $nbrplacedispo;

        return $this;
    }
    public function reserverAtelier(int $atelierId, User $user, EntityManagerInterface $entityManager)
    {
        $atelier = $entityManager->getRepository(Atelier::class)->find($atelierId);
    
        if (!$atelier) {
            throw new \Exception("L'atelier n'existe pas.");
        }
            if ($atelier->getNbrplacedispo() <= 0) {
            throw new \Exception("Cet atelier est complet, il n'y a plus de place..");
        }
        $atelier->addUser($user);
        $atelier->setNbrplacedispo($atelier->getNbrplacedispo() - 1);
        $entityManager->persist($atelier);
            $entityManager->flush();
    }

    /**
     * @return Collection<int, Dechet>
     */
    public function getDechet(): Collection
    {
        return $this->dechet;
    }

    public function addDechet(Dechet $dechet): static
    {
        if (!$this->dechet->contains($dechet)) {
            $this->dechet->add($dechet);
            $dechet->setDechet($this);
        }

        return $this;
    }

    public function removeDechet(Dechet $dechet): static
    {
        if ($this->dechet->removeElement($dechet)) {
            // set the owning side to null (unless already changed)
            if ($dechet->getDechet() === $this) {
                $dechet->setDechet(null);
            }
        }

        return $this;
    }
       // Getters et Setters
  
       public function getTitle(): string
       {
           return $this->title;
       }
   
       public function setTitle(string $title): self
       {
           $this->title = $title;
           return $this;
       }
   
       public function getStartAt(): \DateTimeInterface
       {
           return $this->startAt;
       }
   
       public function setStartAt(\DateTimeInterface $startAt): self
       {
           $this->startAt = $startAt;
           return $this;
       }
   
       public function getEndAt(): ?\DateTimeInterface
       {
           return $this->endAt;
       }
   
       public function setEndAt(?\DateTimeInterface $endAt): self
       {
           $this->endAt = $endAt;
           return $this;
       }
   

}

src/Controller/testbackController.php
<?php

namespace App\Controller;

use App\Entity\Atelier;
use App\Form\AtelierType;
use App\Repository\AtelierRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Knp\Component\Pager\PaginatorInterface;
#[Route('/testBack')]
final class testbackController extends AbstractController
{
    #[Route(name: 'app_testBack_index2', methods: ['GET'])]
   // public function index2(AtelierRepository $atelierRepository): Response
   public function index2(Request $request, AtelierRepository $atelierRepository, PaginatorInterface $paginator): Response
    {
        $query = $atelierRepository->findAll();
        $pagination = $paginator->paginate(
            $query, // Donneili bch namlou pagination
            $request->query->getInt('page', 1), // Num page 
            6 // nbr element par page 
        );
        return $this->render('testBack/index2.html.twig', [
            'pagination' => $pagination,
        ]);
        /*return $this->render('testBack/index2.html.twig', [
            'ateliers' => $atelierRepository->findAll(),
        ]);*/
    }

    #[Route('/new', name: 'app_testBack_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $em): Response
    {
        $atelier = new Atelier();
        $form = $this->createForm(AtelierType::class, $atelier);
        $form->handleRequest($request);
        dump($form->getData()->getDateAtelier());

        if ($form->isSubmitted() && $form->isValid()) 
        {
            // Vérifie si un atelier existe déjà à la même date
           $existingAtelier = $em->getRepository(Atelier::class)->findOneBy([
                'date_atelier' => $atelier->getDateAtelier()
            ]);
    
            if ($existingAtelier) {
                $this->addFlash('error', "Il existe déjà un atelier le " . $atelier->getDateAtelier()->format('Y-m-d') . " avec le nom : " . $existingAtelier->getNom());
                return $this->redirectToRoute('app_testBack_new');
            }
            
            else {
            // Si pas de conflit de date, persister l'atelier
            $em->persist($atelier);
            $em->flush();
            $this->addFlash('success', "L'atelier a été ajouté avec succès.");
            return $this->redirectToRoute('app_testBack_index2', [], Response::HTTP_SEE_OTHER);
            }
        }
    
        return $this->render('testBack/new.html.twig', [
            'atelier' => $atelier,
            'form' => $form,
        ]);
    }
    

      
    #[Route('/{id}', name: 'app_testBack_show', methods: ['GET'])]
    public function show(Atelier $atelier): Response
    {
        return $this->render('testBack/show.html.twig', [
            'atelier' => $atelier,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_testBack_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Atelier $atelier, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(AtelierType::class, $atelier);
        $form->handleRequest($request);
        dump($form->getData()->getDateAtelier());

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_testBack_index2', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('testBack/edit.html.twig', [
            'atelier' => $atelier,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_testBack_delete', methods: ['POST'])]
    public function delete(Request $request, Atelier $atelier, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$atelier->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($atelier);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_testBack_index2', [], Response::HTTP_SEE_OTHER);
    }
}

templates/testBack/_delete_form.html.twig
<form method="post" action="{{ path('app_atelier_delete', {'id': atelier.id}) }}" onsubmit="return confirm('Etes-vous sûr de vouloir supprimer cet élément?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ atelier.id) }}">
     <button class="btn">Supprimer</button>
</form>

templates/testBack/_footer.html.twig
<footer class="footer">
  <div class="d-sm-flex justify-content-center justify-content-sm-between">
    <span class="text-muted text-center text-sm-left d-block d-sm-inline-block">Copyright © 2023 <a href="https://www.bootstrapdash.com/" target="_blank">BootstrapDash</a>. All rights reserved.</span>
    <span class="float-none float-sm-right d-block mt-1 mt-sm-0 text-center">Hand-crafted & made with <i class="mdi mdi-heart text-danger"></i></span>
  </div>
</footer>

templates/testBack/_form.html.twig
{{ form_start(form,{'attr': {'novalidate': 'novalidate'}}) }}
<center>
<table>
<tr>
    <td>{{form_label(form.nom,"nom")}}</td>
    <td>{{form_widget(form.nom)}}</td>
    <td>{{form_errors(form.nom)}}</td>
</tr>
<tr>
    <td>{{form_label(form.description,"description")}}</td>
    <td>{{form_widget(form.description)}}</td>
    <td>{{form_errors(form.description)}}</td>
</tr>

<tr>
    <td>{{form_label(form.date_atelier,"dateAtelier")}}</td>
    <td>{{form_widget(form.date_atelier)}}</td>
    <td>{{form_errors(form.date_atelier)}}</td>
</tr>
<tr>
    <td>{{form_label(form.capacite_max,"capacite_max")}}</td>
    <td>{{form_widget(form.capacite_max)}}</td>
    <td>{{form_errors(form.capacite_max)}}</td>
</tr>
<tr>
    <td>{{form_label(form.prix,"prix")}}</td>
    <td>{{form_widget(form.prix)}}</td>
    <td>{{form_errors(form.prix)}}</td>
</tr>
<tr>
    <td>{{form_label(form.statut,"statut")}}</td>
    <td>{{form_widget(form.statut)}}</td>
    <td>{{form_errors(form.statut)}}</td>
</tr>
</table>
</center>
<br>
    {{form_widget(form.save)}}
{{form_end(form)}}

templates/testBack/_navbar.html.twig
<nav class="navbar default-layout-navbar col-lg-12 col-12 p-0 fixed-top d-flex flex-row">
  <div class="text-center navbar-brand-wrapper d-flex align-items-center justify-content-start">
    <a class="navbar-brand brand-logo" href="../index.html"><img src="../assets/images/logo.svg" alt="logo" /></a>
    <a class="navbar-brand brand-logo-mini" href="../index.html"><img src="../assets/images/logo-mini.svg" alt="logo" /></a>
  </div>
  <div class="navbar-menu-wrapper d-flex align-items-stretch">
    <button class="navbar-toggler navbar-toggler align-self-center" type="button" data-toggle="minimize">
      <span class="mdi mdi-menu"></span>
    </button>
    <div class="search-field d-none d-md-block">
      <form class="d-flex align-items-center h-100" action="#">
        <div class="input-group">
          <div class="input-group-prepend bg-transparent">
            <i class="input-group-text border-0 mdi mdi-magnify"></i>
          </div>
          <input type="text" class="form-control bg-transparent border-0" placeholder="Search projects">
        </div>
      </form>
    </div>
    <ul class="navbar-nav navbar-nav-right">
      <li class="nav-item nav-profile dropdown">
        <a class="nav-link dropdown-toggle" id="profileDropdown" href="#" data-bs-toggle="dropdown" aria-expanded="false">
          <div class="nav-profile-img">
            <img src="../assets/images/faces/face1.jpg" alt="image">
            <span class="availability-status online"></span>
          </div>
          <div class="nav-profile-text">
            <p class="mb-1 text-black">David Greymaax</p>
          </div>
        </a>
        <div class="dropdown-menu navbar-dropdown" aria-labelledby="profileDropdown">
          <a class="dropdown-item" href="#">
            <i class="mdi mdi-cached me-2 text-success"></i> Activity Log </a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">
            <i class="mdi mdi-logout me-2 text-primary"></i> Signout </a>
        </div>
      </li>
      <li class="nav-item d-none d-lg-block full-screen-link">
        <a class="nav-link">
          <i class="mdi mdi-fullscreen" id="fullscreen-button"></i>
        </a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link count-indicator dropdown-toggle" id="messageDropdown" href="#" data-bs-toggle="dropdown" aria-expanded="false">
          <i class="mdi mdi-email-outline"></i>
          <span class="count-symbol bg-warning"></span>
        </a>
        <div class="dropdown-menu dropdown-menu-end navbar-dropdown preview-list" aria-labelledby="messageDropdown">
          <h6 class="p-3 mb-0">Messages</h6>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item preview-item">
            <div class="preview-thumbnail">
              <img src="../assets/images/faces/face4.jpg" alt="image" class="profile-pic">
            </div>
            <div class="preview-item-content d-flex align-items-start flex-column justify-content-center">
              <h6 class="preview-subject ellipsis mb-1 font-weight-normal">Mark send you a message</h6>
              <p class="text-gray mb-0"> 1 Minutes ago </p>
            </div>
          </a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item preview-item">
            <div class="preview-thumbnail">
              <img src="../assets/images/faces/face2.jpg" alt="image" class="profile-pic">
            </div>
            <div class="preview-item-content d-flex align-items-start flex-column justify-content-center">
              <h6 class="preview-subject ellipsis mb-1 font-weight-normal">Cregh send you a message</h6>
              <p class="text-gray mb-0"> 15 Minutes ago </p>
            </div>
          </a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item preview-item">
            <div class="preview-thumbnail">
              <img src="../assets/images/faces/face3.jpg" alt="image" class="profile-pic">
            </div>
            <div class="preview-item-content d-flex align-items-start flex-column justify-content-center">
              <h6 class="preview-subject ellipsis mb-1 font-weight-normal">Profile picture updated</h6>
              <p class="text-gray mb-0"> 18 Minutes ago </p>
            </div>
          </a>
          <div class="dropdown-divider"></div>
          <h6 class="p-3 mb-0 text-center">4 new messages</h6>
        </div>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link count-indicator dropdown-toggle" id="notificationDropdown" href="#" data-bs-toggle="dropdown">
          <i class="mdi mdi-bell-outline"></i>
          <span class="count-symbol bg-danger"></span>
        </a>
        <div class="dropdown-menu dropdown-menu-end navbar-dropdown preview-list" aria-labelledby="notificationDropdown">
          <h6 class="p-3 mb-0">Notifications</h6>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item preview-item">
            <div class="preview-thumbnail">
              <div class="preview-icon bg-success">
                <i class="mdi mdi-calendar"></i>
              </div>
            </div>
            <div class="preview-item-content d-flex align-items-start flex-column justify-content-center">
              <h6 class="preview-subject font-weight-normal mb-1">Event today</h6>
              <p class="text-gray ellipsis mb-0"> Just a reminder that you have an event today </p>
            </div>
          </a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item preview-item">
            <div class="preview-thumbnail">
              <div class="preview-icon bg-warning">
                <i class="mdi mdi-cog"></i>
              </div>
            </div>
            <div class="preview-item-content d-flex align-items-start flex-column justify-content-center">
              <h6 class="preview-subject font-weight-normal mb-1">Settings</h6>
              <p class="text-gray ellipsis mb-0"> Update dashboard </p>
            </div>
          </a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item preview-item">
            <div class="preview-thumbnail">
              <div class="preview-icon bg-info">
                <i class="mdi mdi-link-variant"></i>
              </div>
            </div>
            <div class="preview-item-content d-flex align-items-start flex-column justify-content-center">
              <h6 class="preview-subject font-weight-normal mb-1">Launch Admin</h6>
              <p class="text-gray ellipsis mb-0"> New admin wow! </p>
            </div>
          </a>
          <div class="dropdown-divider"></div>
          <h6 class="p-3 mb-0 text-center">See all notifications</h6>
        </div>
      </li>
      <li class="nav-item nav-logout d-none d-lg-block">
        <a class="nav-link" href="#">
          <i class="mdi mdi-power"></i>
        </a>
      </li>
      <li class="nav-item nav-settings d-none d-lg-block">
        <a class="nav-link" href="#">
          <i class="mdi mdi-format-line-spacing"></i>
        </a>
      </li>
    </ul>
    <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button" data-toggle="offcanvas">
      <span class="mdi mdi-menu"></span>
    </button>
  </div>
</nav>

templates/testBack/_sidebar.html.twig
<nav class="sidebar sidebar-offcanvas" id="sidebar">
  <ul class="nav">
    <li class="nav-item nav-profile">
      <a href="#" class="nav-link">
        <div class="nav-profile-image">
          <img src="../assets/images/faces/face1.jpg" alt="profile" />
          <span class="login-status online"></span>
          <!--change to offline or busy as needed-->
        </div>
        <div class="nav-profile-text d-flex flex-column">
          <span class="font-weight-bold mb-2">David Grey. H</span>
          <span class="text-secondary text-small">Project Manager</span>
        </div>
        <i class="mdi mdi-bookmark-check text-success nav-profile-badge"></i>
      </a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="../index.html">
        <span class="menu-title">Dashboard</span>
        <i class="mdi mdi-home menu-icon"></i>
      </a>
    </li>
    <li class="nav-item">
      <a class="nav-link" data-bs-toggle="collapse" href="#ui-basic" aria-expanded="false" aria-controls="ui-basic">
        <span class="menu-title">Basic UI Elements</span>
        <i class="menu-arrow"></i>
        <i class="mdi mdi-crosshairs-gps menu-icon"></i>
      </a>
      <div class="collapse" id="ui-basic">
        <ul class="nav flex-column sub-menu">
          <li class="nav-item">
            <a class="nav-link" href="../pages/ui-features/buttons.html">Buttons</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="../pages/ui-features/dropdowns.html">Dropdowns</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="../pages/ui-features/typography.html">Typography</a>
          </li>
        </ul>
      </div>
    </li>
    <li class="nav-item">
      <a class="nav-link" data-bs-toggle="collapse" href="#icons" aria-expanded="false" aria-controls="icons">
        <span class="menu-title">Icons</span>
        <i class="mdi mdi-contacts menu-icon"></i>
      </a>
      <div class="collapse" id="icons">
        <ul class="nav flex-column sub-menu">
          <li class="nav-item">
            <a class="nav-link" href="../pages/icons/font-awesome.html">Font Awesome</a>
          </li>
        </ul>
      </div>
    </li>
    <li class="nav-item">
      <a class="nav-link" data-bs-toggle="collapse" href="#forms" aria-expanded="false" aria-controls="forms">
        <span class="menu-title">Forms</span>
        <i class="mdi mdi-format-list-bulleted menu-icon"></i>
      </a>
      <div class="collapse" id="forms">
        <ul class="nav flex-column sub-menu">
          <li class="nav-item">
            <a class="nav-link" href="../pages/forms/basic_elements.html">Form Elements</a>
          </li>
        </ul>
      </div>
    </li>
    <li class="nav-item">
      <a class="nav-link" data-bs-toggle="collapse" href="#charts" aria-expanded="false" aria-controls="charts">
        <span class="menu-title">Charts</span>
        <i class="mdi mdi-chart-bar menu-icon"></i>
      </a>
      <div class="collapse" id="charts">
        <ul class="nav flex-column sub-menu">
          <li class="nav-item">
            <a class="nav-link" href="../pages/charts/chartjs.html">ChartJs</a>
          </li>
        </ul>
      </div>
    </li>
    <li class="nav-item">
      <a class="nav-link" data-bs-toggle="collapse" href="#tables" aria-expanded="false" aria-controls="tables">
        <span class="menu-title">Tables</span>
        <i class="mdi mdi-table-large menu-icon"></i>
      </a>
      <div class="collapse" id="tables">
        <ul class="nav flex-column sub-menu">
          <li class="nav-item">
            <a class="nav-link" href="../pages/tables/basic-table.html">Basic table</a>
          </li>
        </ul>
      </div>
    </li>
    <li class="nav-item">
      <a class="nav-link" data-bs-toggle="collapse" href="#auth" aria-expanded="false" aria-controls="auth">
        <span class="menu-title">User Pages</span>
        <i class="menu-arrow"></i>
        <i class="mdi mdi-lock menu-icon"></i>
      </a>
      <div class="collapse" id="auth">
        <ul class="nav flex-column sub-menu">
          <li class="nav-item">
            <a class="nav-link" href="../pages/samples/blank-page.html"> Blank Page </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="../pages/samples/login.html"> Login </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="../pages/samples/register.html"> Register </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="../pages/samples/error-404.html"> 404 </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="../pages/samples/error-500.html"> 500 </a>
          </li>
        </ul>
      </div>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="../docs/documentation.html" target="_blank">
        <span class="menu-title">Documentation</span>
        <i class="mdi mdi-file-document-box menu-icon"></i>
      </a>
    </li>
  </ul>
</nav>

templates/testBack/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Atelier{% endblock %}

{% block body %}
    <h1>Atelier</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ atelier.id }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ atelier.nom }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ atelier.description }}</td>
            </tr>
            <tr>
                <th>Date_atelier</th>
                <td>{{ atelier.dateAtelier ? atelier.dateAtelier|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Capacite_max</th>
                <td>{{ atelier.capaciteMax }}</td>
            </tr>
            <tr>
                <th>Prix</th>
                <td>{{ atelier.prix }}</td>
            </tr>
        {#   <tr>
                <th>IdUser</th>
                <td>{{ atelier.idUser }}</td>
            </tr> #}
            <tr>
                <th>Statut</th>
                <td>{{ atelier.statut }}</td>
            </tr>
           {# <tr>
                <th>Role</th>
                <td>{{ atelier.Role }}</td>
            </tr> #}
        </tbody>
    </table>

    <a href="{{ path('app_atelier_index') }}">Revenir à list</a>

    <a href="{{ path('app_atelier_edit', {'id': atelier.id}) }}">Modifier</a>

    {{ include('atelier/_delete_form.html.twig') }}
{% endblock %}